ALTER TABLE `ADDRESS` DROP FOREIGN KEY `EMPLOYEE_ID_FK`;
ALTER TABLE `EMPLOYEE` DROP FOREIGN KEY `DEPARTMENT_ID_FK`;
TRUNCATE TABLE `SALES_EMPLOYEE`;
TRUNCATE TABLE `ADDRESS`;
TRUNCATE TABLE `EMPLOYEE`;
TRUNCATE TABLE `DEPARTMENT`;
TRUNCATE TABLE `SALES_REGION`;
ALTER TABLE `ADDRESS` ADD CONSTRAINT `EMPLOYEE_ID_FK` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `EMPLOYEE` (`ID`);
ALTER TABLE `EMPLOYEE` ADD CONSTRAINT `DEPARTMENT_ID_FK` FOREIGN KEY (`DEPARTMENT_ID`) REFERENCES `DEPARTMENT` (`ID`)
